spring:
  mvc:
    static-path-pattern: /static/**
  web:
    resources:
      # spring 이 정적 파일 요청을 받을 때 해당 파일을 찾는 경로
      static-locations: file:media/,classpath:/static

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 30MB
